services:
  db:
    image: mysql
    container_name: db_dt
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer_dt
    restart: always
    ports:
      - 8080:8080

  mongodb:
    image: mongo:7.0
    container_name: mongo_otomo
    environment:
      MONGO_INITDB_ROOT_USERNAME: hobby
      MONGO_INITDB_ROOT_PASSWORD: hobby
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
